# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsreferences',
            name='product',
        ),
        migrations.RemoveField(
            model_name='products',
            name='user',
        ),
        migrations.AddField(
            model_name='products',
            name='product_description',
            field=models.CharField(default='sin dato', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='product_tags',
            field=models.CharField(default='sin dato', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='product_name',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='ProductsReferences',
        ),
    ]
