# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0002_auto_20170128_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_description',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_tags',
            field=models.CharField(max_length=2000),
        ),
    ]
